/**
 * Database connection — singleton backed by better-sqlite3 + Drizzle ORM.
 *
 * The DB file lives at `<DATA_PATH>/pi-tree.db` (default: ~/.local/share/pi-tree/).
 *
 * Schema migrations are auto-generated by `drizzle-kit generate` and live in
 * `packages/server/drizzle/`. On startup, `migrate()` from drizzle-orm applies
 * any pending migrations automatically — users never run migrations manually.
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import { mkdirSync } from "node:fs";
import Database from "better-sqlite3";
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import * as schema from "./schema.js";

// Re-export schema tables for convenient imports
export {
  users,
  sources,
  userSessions,
  userSourceConfig,
  userSourceProgress,
  glossaryEntries,
  tags,
  sourceTags,
} from "./schema.js";

// ---------------------------------------------------------------------------
// Migrations folder — resolved relative to this file so it works in both
// dev (src/db/) and production (dist/db/) builds.
//
//   dev:  packages/server/src/db/index.ts  → ../../drizzle
//   prod: packages/server/dist/db/index.js → ../../drizzle
// ---------------------------------------------------------------------------

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const MIGRATIONS_FOLDER = path.resolve(__dirname, "../../drizzle");

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

let _db: BetterSQLite3Database<typeof schema> | null = null;

/**
 * Get the Drizzle database instance (lazy-initialized on first call).
 * Creates the DB file and directory if they don't exist, and runs
 * any pending schema migrations.
 */
export function getDb(): BetterSQLite3Database<typeof schema> {
  if (_db) return _db;

  const dataPath =
    process.env.DATA_PATH ??
    path.join(process.env.HOME ?? "~", ".local", "share", "pi-tree");

  const dbDir = dataPath;
  const dbPath = path.join(dbDir, "pi-tree.db");

  // Ensure the directory exists
  mkdirSync(dbDir, { recursive: true });

  console.log(`[db] Opening database at ${dbPath}`);
  const sqlite = new Database(dbPath);

  // Enable WAL mode for better concurrent read performance
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");

  _db = drizzle(sqlite, { schema });

  // Run pending migrations (auto-generated SQL in drizzle/ folder)
  runMigrations(_db);

  return _db;
}

/**
 * Reset the database connection. Used in tests to get a fresh DB.
 * Closes the underlying SQLite connection and clears the singleton.
 */
export function resetDb(): void {
  if (_db) {
    try {
      // Drizzle wraps the sqlite instance; close it to release the file lock
      (_db as any)._.session.client.close();
    } catch {
      // Ignore if already closed
    }
    _db = null;
  }
}

// ---------------------------------------------------------------------------
// Migration runner
//
// Reads SQL files from `packages/server/drizzle/` and applies pending ones.
// Drizzle's migrator tracks applied migrations in `__drizzle_migrations`.
//
// Workflow for developers:
//   1. Edit schema.ts
//   2. Run `npm run db:generate -w @pi-tree/server`
//   3. Review the generated SQL in drizzle/
//   4. Commit and push — users get auto-migration on next startup
// ---------------------------------------------------------------------------

function runMigrations(db: BetterSQLite3Database<typeof schema>): void {
  console.log(`[db] Checking for pending migrations...`);
  migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  console.log("[db] Migrations up to date");
}

